# Generated by Django 4.0.4 on 2022-09-04 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(max_length=200)),
                ('cover_photo', models.ImageField(blank=True, upload_to='cover_images')),
                ('type_of_package', models.CharField(choices=[('BASIC', 'Basic'), ('STANDARD', 'Standard'), ('STANDARD_PLUS', 'Standard plus')], max_length=100)),
                ('videos', models.FileField(blank=True, upload_to='videos')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(blank=True, upload_to='profile_photos')),
                ('courses', models.ManyToManyField(null=True, to='courses.course')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videos', models.FileField(blank=True, upload_to='videos')),
                ('course_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
    ]
